### PR TITLE
More fixes

### PR DESCRIPTION
**Pull request by aphelionz**

### CODE REVIEW

**Comment by oed** [comment]
Thanks for the PR @aphelionz! Usually we make all changes to develop, and then only use master to merge releases. Will likely use this as a blueprint when we update the orbitdb version :D

**Comment by aphelionz** [comment]
Sounds good to me, feel free to close this at your leisure.

**Comment by oed** [comment]
Keeping open for findability until addressed :)

**Comment by oed** [comment]
Closing, this is now being tracked here: #617

**Pull request closed without merging**
