### PR TITLE
fix: 3id serialize normalized address

### PR DESCRIPTION
**Pull request by zachferland**
Marked do not merge until done following up, with fix, same stores are derived in trust wallet now, but seeing other issues (might be with state there already)

### CODE REVIEW

**Comment by zachferland** [comment]
Also anyone who created a profile in trust wallet, would lose that store when we make this change

**Comment by zachferland** [comment]
should probably also renormalize whats in local storage already and rewrite as well, otherwise if you tried to open in trustwallet already it would not work

**Comment by zachferland** [comment]
unless recent change from trust wallet, than only profile created since that change would be lost, must be minimal to none

**Comment by oed** [comment]
Oh damn! This completely explains why profiles are lost in trust wallet! We're just lucky that it hasn't happened elsewhere.

**Comment by zachferland** [comment]
yup, can just go into develop 👍 

also added a test for this case

**Pull request merged**
