### PR TITLE
fix: close ipfs, so reopen works

### PR DESCRIPTION
**Pull request by zachferland**
This fixes, where you openBox, close and then try to open again, now onsyncdone is called both times. 
This was the minimal code fix but after looking into it more it looks like ipfs/pubsub with multiple instances causes some issues, I think @oed  has mentioned this before. So there could be some issues around caching in these instances that cause pubsub to not send any messages and for onsyncdone to not be returned. I might makes sense to generally use the global ipfs/orbitdb and not close them, just keep open and then connect if already available. 

Seem likes ipfs was caching something, since peers were listed before onNewPeer was even called once. And then anytime you tried to create a new pubSub (after one was already created on an instance) it would look like its available but then just would not publish any messages.

Also if you create an ipfs instance, call stop on it, then create a new instance and call stop again it throws an error saying stop was already called. So need to understand what ipfs is doing, seems to keep a singleton instance around or something. Its probably best to treat it as a node/service running in the background instead of we do now.

### CODE REVIEW

**Comment by oed** [comment]
Ugh, the reason it was commented out is because it breaks the tests :/

**Comment by zachferland** [comment]
hahah yeah, something is up with, because like I mentioned after the first time you call, not even on the "same" instance it keeps saying stop was already called. 

I think the solution is to just keep IPFS/orbit in the background, and change the pin db logic a bit, so that it sends on new peer the first, and after just sends when opening again if already connect to the peer

**Comment by oed** [comment]
Ok, yeah that seems alright

**Comment by zachferland** [comment]
This keeps ipfs around and doesn't stop it. Just reuses it if available. More stable than before, fixes much of the weird behavior in stopping/starting and with pubsub.

One thing not clear, is why opening box the second time after closing is much slower than the first time. Something to look into in the future.

**Comment by zachferland** [comment]
@oed  all set now, rewrote over other commits, since the approach completely changed, pretty minimal here

**Pull request merged**
