### PR TITLE
naive fix for #534

### PR DESCRIPTION
**Pull request by Schwartz10**
Closed a different, identical PR bc of a weird commit history. 

@oed I'm sure this is a pretty naive approach to the race condition issue, but it seems to do the trick for me. I'll check with another dev on the team who was also experiencing hanging calls to see if it fixes it for him too and update here.

Would love to get a fix for this issue in to a version <1.10 because I want to avoid this issue

Please let me know your thoughts! Thank you

### CODE REVIEW

**Comment by Schwartz10** [comment]
An update from @chadoh (another dev who was experiencing hanging calls) - he's on Brave browser and saw these warnings in the console:

```
Warning: Given input entry is not allowed in this log and was discarded (no write access).
```
```
Store.js:258 "WARNING! Head hash didn't match the contents
```
```
Warning: Given input entry is not allowed in this log and was discarded (no write access).
```
```
[Violation] 'setInterval' handler took 76ms
```

He can't consistently unlock a box on brave, using code directly from the 3box docs. Either calls hang, or the box unlocks extremely quickly.

**Comment by Schwartz10** [comment]
Hmmm, also not sure this actually fixes the issue i was seeing before. I still get stuck syncing at some point, but can't seem to nail down why or where.

Will drop some more info in the issue ticket

**Comment by oed** [comment]
This makes sense @Schwartz10. I don't see any issues with it 🙂

**Comment by Schwartz10** [comment]
@oed that's great! When do you think we could pull this in and publish a new version?

**Pull request merged**
