### PR TITLE
Chore/update ipfs and web3modal

### PR DESCRIPTION
**Pull request by zachferland**
Just branch for testing

### CODE REVIEW

**Comment by oed** [comment]
@zachferland I just made an update to the ipfs branch fyi.

**Comment by oed** [comment]
@zachferland would you mind making a PR with just the web3modal update? Then we can rebase the ipfs update on that.

**Comment by zachferland** [comment]
yeah ill do that

**Comment by oed** [comment]
Ty 🙏

**Comment by zachferland** [comment]
https://github.com/3box/3box-js/pull/833/files @oed

**Pull request closed without merging**
