### PR TITLE
Typescript binding(s) for 3Box

### PR DESCRIPTION
**Pull request by kuhnchris**
Typescript prototypish-ed bindings. Only tested with getProfile right now. Need more usecases for test(s).

### CODE REVIEW

**Comment by oed** [comment]
Hey @kuhnchris! This is great. Would love to merge it, but I'm afraid it will become obsolete quite quickly as the api develops. The reason being that none on our team are very familiar with typescript and it's best practices. 
Maybe it would be better to have this in a separate repo for now, but I'm not sure. What do you think?

**Comment by kuhnchris** [comment]
Hey there @oed - we talked about this on the discord already a bit, but let's recollect here:
The best way would be to commit this to the DefinitlyTyped Repository and tag it with the API version number, that also makes sure that we take into account when the API changes. 

Do you have any policy in place regarding "breaking" changes? 
The most important thing here is to keep at least some kind of accuracy so people can use the bindings. If they need "newer" features they would request it either in the DefinitlyTyped repository, here, or we create a own 3box.ts repository. 
Either way is fine by me, let me know!

Thanks

**Comment by oed** [comment]
Thanks for the summary @kuhnchris. It does seem like committing it to the DefinitlyTyped Repository seems like the best approach indeed. As for breaking changes we follow [Semantic Versioning](https://semver.org/) which should tell you if there are any breaking changes 🙂

**Comment by oed** [comment]
Hey @kuhnchris do you have everything you need here? Can I close this?

**Comment by kuhnchris** [comment]
We can prolly close it, yes. I will get int contact with the DefinitlyTyped repository to get it in. Thanks for the support

**Comment by oed** [comment]
Thanks @kuhnchris!

**Comment by eshohet** [comment]
Any updates on this?

**Comment by hammadj** [comment]
@oed Would love to see updated TS types for 3box

**Pull request closed without merging**
