### PR TITLE
Update keys list.

### PR DESCRIPTION
**Pull request by IMRFeng**
This PR only updates the keys list for the public and private data of the linkedref.io

### CODE REVIEW

**Comment by zachferland** [comment]
Related to https://github.com/3box/3box/pull/437

**Comment by IMRFeng** [comment]
Thanks @zachferland, I'd replied in the other PR.

**Comment by oed** [comment]
@IMRFeng I'm closing this since we have moved the "key conventions" file to the 3box/3box repo. You can make an update to your PR there, or maybe wait with doing this until your project is live :)

**Comment by IMRFeng** [comment]
@oed That's very interesting, I did not see anywhere mentioned the dapp must be a live application in the definition of done and requirements of your bounty but got "or dapp code that has successfully integrated with 3Box methods mehtioned above" in the requirements.

**Pull request closed without merging**
