### PR TITLE
Update orbit-db package

### PR DESCRIPTION
**Pull request by aturX**
[Update This](https://github.com/orbitdb/orbit-db/issues/830)

### CODE REVIEW

**Comment by oed** [comment]
Thanks @aturX Do you know what was changed between `0.24.3` and `0.25.1`? Can't find a change log on orbitdb.

**Comment by aturX** [comment]
I not sure all.  Maby it was fixed about this [issue orbit-db](https://github.com/orbitdb/orbit-db/issues/821)   or  [issues](https://github.com/orbitdb/orbit-db-keystore/issues/45)

I not sure now but want to just try it , and check that  [bug](https://github.com/3box/3box-js/issues/897)  .

Make sure it's fixed

**Comment by aphelionz** [comment]
Not much was changed. There was only a couple things that needed to be updated to get 0.49.0 + 0.6.0 support

https://github.com/orbitdb/orbit-db/pull/831

**Comment by aphelionz** [comment]
Running `npm outdated` on the repo shows some additional packages you might want to consider updating as well:

```
ipfs                                               0.46.0          0.46.1          0.49.1  3box
ipfs-log                                            4.6.1           4.6.2           4.6.2  3box
ipfs-repo                                           3.0.3           3.0.3           6.0.3  3box
is-ipfs                                             1.0.3           1.0.3           2.0.0  3box
libp2p-pubsub                                       0.4.6           0.4.7           0.6.0  3box
orbit-db                                           0.24.2          0.24.2          0.25.1  3box
orbit-db-identity-provider                          0.3.0           0.3.1           0.3.1  3box
```

(list not complete)

**Comment by oed** [comment]
Thanks @aphelionz! We tend to take our time with updating js-ipfs since it has a lot of surface area and we want to be sure not to break things when we update. Do you know if this new OrbitDB version works with `ipfs@0.46`?

**Comment by aphelionz** [comment]
It depends on the behavior of `ipfs.add` - in 0.49 it returns a single object and in other versions it returns an Async Iterable of one :yum: 

But since the tests are passing with OrbitDB 0.25.1 and js-ipfs 0.46.x here, I'd say it's ok

**Comment by aphelionz** [comment]
Also, the above `ipfs.add` issue is only for `Log#toSnapshot`so if you're not using that you're probably OK

**Comment by oed** [comment]
Thanks for the clarification @aphelionz. Will try to have this reviewed for a release soon.

**Comment by aphelionz** [comment]
Oh, there may be an IPFS repo migration involved as well 😅😅

**Comment by oed** [comment]
Yeah, we are likely not going to update ipfs at this time :)

**Comment by zachferland** [comment]
Seeing same issues as here - https://github.com/orbitdb/orbit-db/issues/839 

Although it appears sub dependencies introduced this, and not 0.25.1, but is blocking

**Comment by aphelionz** [comment]
Handled in https://github.com/orbitdb/orbit-db/pull/837, but trying to figure out the go-ipfs timeouts 😝

**Pull request closed without merging**
